In [1]:
for i in [1,2,3,4,5]:
    print(i**2)

1
4
9
16
25


In [2]:
for i in range(6):
    print(i**2)

0
1
4
9
16
25


In [4]:
colors=['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i])

red
green
yellow
purple


In [5]:
for color in colors:
    print(color)

red
green
yellow
purple


In [7]:
colors =['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i])

purple
yellow
green
red


In [8]:
for i in reversed(colors):
    print(i)

purple
yellow
green
red


In [12]:
for i in sorted(colors):
    print(i)

green
purple
red
yellow


In [14]:
for color in sorted(colors,reverse=True):
    print(color)

yellow
red
purple
green


In [15]:
import pandas as pd

In [19]:
dt ={'Id':[11,12,13,14,15],
   'first_name':['A','B','C','D','E'],
   'company':['aa','bb','cc','dd','ee'],
    'address':['hyd','hyd','hyd','hyd','hyd']}
mydt=pd.DataFrame(dt)

In [18]:
print(mydt)

   Id first_name company address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [20]:
import numpy as np

In [21]:
li =[1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [22]:
array =np.array(li)
print(array)

[1 2 3 4 5]


In [23]:
a1 =np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [24]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [26]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
